name: Release Please

on:
  push:
    branches:
      - main
      - master
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # 'simple' will just bump version in the release tag and maintain CHANGELOG.md
          release-type: simple
